name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-rampage-tracker:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PLAYERS: ${{ secrets.PLAYERS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x' # Use the appropriate .NET version

    - name: Restore dependencies
      run: dotnet restore Dota2RampageTracker/RampageTracker.sln

    - name: Build the project
      run: dotnet build --configuration Release Dota2RampageTracker/RampageTracker.sln

    - name: Run Rampage Tracker
      run: dotnet run --project Dota2RampageTracker/OpenDotaRampage/OpenDotaRampage.csproj
      env:
        ApiKey: ${{ secrets.API_KEY }}
        Players: ${{ secrets.PLAYERS }}
        GitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Daily update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
