name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore 'Dota2RampageTracker/OpenDotaRampage/OpenDotaRampage.csproj'

      - name: Build
        run: dotnet build 'Dota2RampageTracker/OpenDotaRampage/OpenDotaRampage.csproj' --no-restore

      - name: Run the application
        run: dotnet run --project 'Dota2RampageTracker/OpenDotaRampage/OpenDotaRampage.csproj'
