name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-rampage-tracker:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PLAYERS: ${{ secrets.PLAYERS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore 'Dota2RampageTracker/OpenDotaRampage/OpenDotaRampage.csproj'

      - name: Build
        run: dotnet build 'Dota2RampageTracker/OpenDotaRampage/OpenDotaRampage.csproj' --no-restore

      - name: Run the application
        run: dotnet run --project 'Dota2RampageTracker/OpenDotaRampage/OpenDotaRampage.csproj'

      env:
        ApiKey: ${{ secrets.API_KEY }}
        Players: ${{ secrets.PLAYERS }}
        GitHubToken: ${{ secrets.GH_TOKEN }}
